### ISSUE TITLE
Moving server FAQ from cepdnaclk.github.io to faq.ce.pdn.ac.lk

### ISSUE THREAD

**Issue by gihanjayatilaka** [cepdnaclk/faq.ce.pdn.ac.lk#20]
1. Move https://github.com/cepdnaclk/cepdnaclk.github.io/tree/master/servers to https://faq.ce.pdn.ac.lk/network-n-servers/
2. Delete the first one.
3. Inform Dr. @damayanthiHerath about this change so she can update the link on ce.pdn.ac.lk. >> about us >> Facilities >> GPU Server.

**Comment by NuwanJ** [comment]
TODO: 
- [ ] Move content from https://ce-pdn-ac-lk.com/cewiki/server_use:use_of_servers to here

**Comment by NuwanJ** [comment]
Added a redirection from `https://cepdnaclk.github.io/sites/servers/` to `https://faq.ce.pdn.ac.lk/network-n-servers/`
