### ISSUE TITLE
Remove Server admin contact information

### ISSUE THREAD

**Issue by gihanjayatilaka** [cepdnaclk/faq.ce.pdn.ac.lk#57]
We have @AmilaIndika789 's contact information here (https://faq.ce.pdn.ac.lk/network-n-servers/contact-network-admin/). 

Ask Amila if he is okay with people contacting him about these issues now.
If not, remove his info and add the contact information of the HoD until a new server admin is recruited.

**Comment by AmilaIndika789** [comment]
I'm checking my eng mail less frequently now. Therefore, please add the new server admin's contact information and remove my contact information. Thanks!

**Comment by NuwanJ** [comment]
Closing with 6b97524
