### ISSUE TITLE
Jupyter notebooks (Aiken)

### ISSUE THREAD

**Issue by gihanjayatilaka** [cepdnaclk/faq.ce.pdn.ac.lk#58]
The current documentation's steps (3,4,5,6) can be simplified by one command 
`jupyter notebook --no-browser --port=8888 --ip=0.0.0.0`.
Once you change this, please notify me via email (https://www.cs.umd.edu/~gihan/contact/) to verify if this is correct before closing the github issue.

**Comment by NuwanJ** [comment]
@gihanjayatilaka 

![image](https://github.com/cepdnaclk/faq.ce.pdn.ac.lk/assets/11540782/f0cc733b-7246-42a5-9f6a-63b8565a2e9c)
