### ISSUE TITLE
Expand all button on https://faq.ce.pdn.ac.lk/home_new/

### ISSUE THREAD

**Issue by gihanjayatilaka** [cepdnaclk/faq.ce.pdn.ac.lk#8]
Hi! What do you think about adding an "expand all" button on https://faq.ce.pdn.ac.lk/home_new/ ?

**Comment by NipunFernando** [comment]
I guess, the "expand all" button is for the pages of each category listing their questions and answers? (Not the home?)

**Comment by NuwanJ** [comment]
@NipunFernando Yes, I think this is about the questions and answers in the "level 3" pages

**Comment by NipunFernando** [comment]
@NuwanJ Hope the new button on General, Network and Servers, etc ... pages does the job. 
![image](https://user-images.githubusercontent.com/73756777/149671649-671cae55-1556-4825-b0e1-9d77b55c0aaf.png)
